CC= gcc
CFLAGS= -Wall -g
LDLIBS= -lm

main: main.o prime.o gcd.o

main.o:  main.c prime.h gcd.h

prime.o: prime.c  prime.h 

gcd: gcd.c gcd.h

.PHONY: clean
clean:
	rm -f *.o a.out core main 
	
.PHONY: all
all: clean main



